/*******************************************************************************
 * @file pwm_node_can_dbc.c
 * @brief Auto-generated CAN message definitions from DBC file.
 *******************************************************************************
 */

/** Includes. *****************************************************************/

#include "pwm_node_can_dbc.h"

/** Private variables. ********************************************************/

static const can_signal_t state_signals[2] = {
    {
        .name = "system_state",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "mcu_temperature",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = -40.0f,
        .min_value = -40.0f,
        .max_value = 215.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t current_alert_signals[4] = {
    {
        .name = "alert_ch1",
        .start_bit = 0,
        .bit_length = 1,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 1.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "alert_ch2",
        .start_bit = 1,
        .bit_length = 1,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 1.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "alert_ch4",
        .start_bit = 2,
        .bit_length = 1,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 1.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "alert_source",
        .start_bit = 3,
        .bit_length = 2,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 2.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t command_servo_signals[7] = {
    {
        .name = "node_id",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "servo_channel",
        .start_bit = 8,
        .bit_length = 3,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_SELECTOR,
        .mux_value = 0,
    },
    {
        .name = "reserved0",
        .start_bit = 11,
        .bit_length = 5,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "target_ch1",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 1,
    },
    {
        .name = "target_ch2",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 2,
    },
    {
        .name = "target_ch3",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 3,
    },
    {
        .name = "target_ch4",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_DEPENDENT,
        .mux_value = 4,
    },
};

static const can_signal_t current_sense_signals[3] = {
    {
        .name = "current_ch1",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "current_ch2",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "current_ch4",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t current_alert_set_signals[3] = {
    {
        .name = "limit_ch1",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "limit_ch2",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "limit_ch4",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t current_limit_response_signals[3] = {
    {
        .name = "limit_ch1",
        .start_bit = 0,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "limit_ch2",
        .start_bit = 16,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "limit_ch4",
        .start_bit = 32,
        .bit_length = 16,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 65535.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t datetime_set_signals[7] = {
    {
        .name = "year",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 99.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "month",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 12.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "date",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "weekday",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "hours",
        .start_bit = 32,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 23.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "minutes",
        .start_bit = 40,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "seconds",
        .start_bit = 48,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t datetime_get_response_signals[7] = {
    {
        .name = "year",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 99.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "month",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 12.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "date",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 31.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "weekday",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 1.0f,
        .max_value = 7.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "hours",
        .start_bit = 32,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 23.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "minutes",
        .start_bit = 40,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "seconds",
        .start_bit = 48,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 59.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t rgb_led_set_signals[3] = {
    {
        .name = "red",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "green",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "blue",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

static const can_signal_t version_get_response_signals[4] = {
    {
        .name = "version_major",
        .start_bit = 0,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "version_minor",
        .start_bit = 8,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "version_patch",
        .start_bit = 16,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
    {
        .name = "version_identifier",
        .start_bit = 24,
        .bit_length = 8,
        .byte_order = CAN_LITTLE_ENDIAN,
        .is_signed = false,
        .scale = 1.0f,
        .offset = 0.0f,
        .min_value = 0.0f,
        .max_value = 255.0f,
        .mux_role = CAN_MUX_NONE,
        .mux_value = 0,
    },
};

/** Public variables. *********************************************************/

const can_message_t dbc_messages[] = {
    {
        .name = "state",
        .message_id = 32,
        .id_mask = 0xFFFFFFFF,
        .dlc = 2,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = state_signals,
        .signal_count = 2,
    },
    {
        .name = "current_alert",
        .message_id = 64,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = current_alert_signals,
        .signal_count = 4,
    },
    {
        .name = "command_servo",
        .message_id = 96,
        .id_mask = 0xFFFFFFFF,
        .dlc = 4,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = command_servo_signals,
        .signal_count = 7,
    },
    {
        .name = "current_sense",
        .message_id = 128,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = current_sense_signals,
        .signal_count = 3,
    },
    {
        .name = "current_alert_set",
        .message_id = 160,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = current_alert_set_signals,
        .signal_count = 3,
    },
    {
        .name = "current_limit_get",
        .message_id = 160,
        .id_mask = 0xFFFFFFFF,
        .dlc = 0,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = 0,
        .signal_count = 0,
    },
    {
        .name = "current_limit_response",
        .message_id = 160,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = current_limit_response_signals,
        .signal_count = 3,
    },
    {
        .name = "datetime_set",
        .message_id = 320,
        .id_mask = 0xFFFFFFFF,
        .dlc = 7,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = datetime_set_signals,
        .signal_count = 7,
    },
    {
        .name = "datetime_get",
        .message_id = 224,
        .id_mask = 0xFFFFFFFF,
        .dlc = 0,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = 0,
        .signal_count = 0,
    },
    {
        .name = "datetime_get_response",
        .message_id = 256,
        .id_mask = 0xFFFFFFFF,
        .dlc = 7,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = datetime_get_response_signals,
        .signal_count = 7,
    },
    {
        .name = "rgb_led_set",
        .message_id = 288,
        .id_mask = 0xFFFFFFFF,
        .dlc = 3,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = rgb_led_set_signals,
        .signal_count = 3,
    },
    {
        .name = "version_get",
        .message_id = 960,
        .id_mask = 0xFFFFFFFF,
        .dlc = 0,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = 0,
        .signal_count = 0,
    },
    {
        .name = "version_get_response",
        .message_id = 992,
        .id_mask = 0xFFFFFFFF,
        .dlc = 4,
        .rx_handler = 0, // (can_rx_handler_t)my_rx_handler_func,
        .tx_handler = 0, // (can_tx_handler_t)my_tx_handler_func,
        .signals = version_get_response_signals,
        .signal_count = 4,
    },
};
